name: Deploy Cloud Function

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-gcp-function:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: csv-to-json
          runtime: 'go116'
          entry_point: Handler
          region: 'europe-west2'
          source_dir: function
